---
categories:
  - id: food
    title: Food
  - id: books
    title: Books

items:
  bread:
    name: Bread
    description: A bread in the game.
    icon: img/items/bread.webp
    category: food
    onUse:
      action: jump
      label: eat_bread
  book:
    name: Ominous Book
    description: An ominous book.
    icon: img/items/book.webp
    category: books
    onUse:
      action: run
      label: read_book
    tag: always_interactable
