screens:
  default:
    background: img/backgrounds/title-screen.png
  diaz_office:
    background: img/backgrounds/diaz-office.jpeg
  case_files:
    background: img/backgrounds/evidence-room.jpeg
  jack_thompson:
    background: img/backgrounds/jack_thompson.png
  arcadia_times:
    background: img/backgrounds/arcadia-times.jpeg
  prototype_wing:
    background: img/backgrounds/prototype_wing.png
  horizon_corp:
    background: img/backgrounds/horizon_corp.png
  sinclair_lab:
    background: img/backgrounds/sinclair-lab.png
  datacenter:
    background: img/backgrounds/datacenter.png
