screens:
  default:
    background: img/backgrounds/title-screen.png
  diaz_office:
    background: img/backgrounds/diaz-office.jpeg
  case_files:
    background: img/backgrounds/evidence-room.jpeg
  jack_thomson:
    background: img/backgrounds/jack_thomson.png
  horizon_exposed:
    background: img/backgrounds/horizon-exposed.png
  prototype_wing:
    background: img/backgrounds/prototype_wing.png
  sinclair_lab:
    background: img/backgrounds/sinclair-lab.png
  datacenter:
    background: img/backgrounds/datacenter.png
  theory_debunked:
    background: img/backgrounds/theory-debunked.png
  detective_missing:
    background: img/backgrounds/detective-missing.png
  thomson_arrested:
    background: img/backgrounds/thomson-arrested.png
  patrick_arrested:
    background: img/backgrounds/patrick-arrested.png
